@SquareApi_HostAddress = http://localhost:5051

GET {{SquareApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SquareApi_HostAddress}}/api/square/
Accept: application/json

###
POST {{SquareApi_HostAddress}}/api/square/
Content-Type: application/json

{
    "Color": "rgb(153,123,123)",
    "X": 2,
    "Y": 2
}

###

PUT {{SquareApi_HostAddress}}/api/square/0
Content-Type: application/json

{
    "Id": 1,
    "Color":"rgb(123,123,123)",
    "X": 1,
    "Y": 1
}

###

GET {{SquareApi_HostAddress}}api/square/1
Accept: application/json

###

DELETE {{SquareApi_HostAddress}}/api/square/1

###